// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxudqqifqnurecnffdra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dWRxcWlmcW51cmVjbmZmZHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTcxNDcsImV4cCI6MjA2Njc5MzE0N30.UHAuCNx_iTDLPmXik22DcwZnJ2wEBM1nSXVrAsEJufI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);